version: "3.2"

services:
  chatbotapp:
    build: 
      context: ./
      dockerfile: build/package/chatbot/Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - LINE_CHANNEL_SECRET=
      - LINE_CHANNEL_TOKEN=
